"""empty message

Revision ID: 68ea33124490
Revises: 6ff66368e3a7
Create Date: 2019-01-03 17:05:18.515739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68ea33124490'
down_revision = '6ff66368e3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False),
    sa.Column('username', sa.String(length=191), nullable=False),
    sa.Column('fullname', sa.String(length=191), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('id_token', sa.String(length=512), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'moderator', 'viewer'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_index('email', table_name='timestamp_model')
    op.drop_index('username', table_name='timestamp_model')
    op.drop_table('timestamp_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timestamp_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('fullname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('id_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=True),
    sa.Column('image', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('role', mysql.ENUM('admin', 'moderator', 'viewer', collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'timestamp_model', ['username'], unique=True)
    op.create_index('email', 'timestamp_model', ['email'], unique=True)
    op.drop_table('user')
    # ### end Alembic commands ###
